[env:curiosity_nano_4809]
platform = atmelmegaavr
board = curiosity_nano_4809
framework = arduino
monitor_speed = 115200

; change microcontroller
board_build.mcu = atmega4809
; change core
board_build.core = MegaCoreX

; change MCU frequency
board_build.f_cpu = 20000000L
build_flags =
    -Isrc
    -Isrc/Hardware
    -Isrc/Logic
lib_deps =
    alby312/AdvancedPID @ ^1.0.0

;board_fuses.osccfg = 0x02


